### ISSUE TITLE
New release to support stdlib >6

### ISSUE THREAD

**Issue by ltning** [deanwilson/puppet-ip_in_range#15]
A new release that does not barf on stdlib > 6.0 would be nice.
By "barf" I mean it causes puppet module to complain that dependencies cannot be resolved. It seems to work just fine in our tests, so I don't think it's broken per se.

**Comment by deanwilson** [comment]
Hi @ltning, thank you for raising this and the PR to fix. You're now using a newer version of the stdlib than I am so fingers crossed :)

I've pushed the new release to the forge `Version 0.0.6 released Jan 4th 2020` but it's the first one built with `pdk` so please let me know if you have any issues with it.
