### ISSUE TITLE
New release to support stdlib >=8

### ISSUE THREAD

**Issue by theinvisible** [deanwilson/puppet-ip_in_range#63]
Hi,

the current Version has a requirement for stdlib like ">= 4.2.2 <7.0.0"

There is already stdlib 8.x out and on updates this package blocks stdlib. 

Would be nice if you could update this package to support stdlib 8.x and als release a new version on puppet forge as there seems to be quite a few current git commits ; )

Thanks & best regards
Rene

**Comment by deanwilson** [comment]
Hello. I've changed the requirement so you can use stdlib <8.0.0 and published the new version to the [Puppetforge](https://forge.puppetlabs.com/modules/deanwilson/ip_in_range/0.0.7). I no longer use this module so if you can i'd recommend migrating away from it.

Apologies for the huge delay in fixing this.
